export const books = [
  {
    id: 1,
    access: "public",
    title: '안나 카레니나',
    author: '레프 톨스토이',
    status: 'read',
    image: 'https://minumsa.minumsa.com/wp-content/blogs.dir/2/files/bookclub-shop/%EB%8C%80%EC%A7%80-10-%EC%82%AC%EB%B3%B8-3-2-500x500.png',
    rating: 5,
    tags: ['고전', '문학'],
    review: '안나의 삶을 어떻게 생각하고 결론 지어야 할까? 사실 아직도 잘 모르겠다. 인간이 살아가면서 부딪히는 자유와 책임을 대신 느껴볼 수 있었음. 톨스토이가 독실해서 권선징악의 결말로 끝낸거 아닐까 생각이 들기도 하지만.. 그리 단순한 책은 아닌거 같다. 안나가 원하는 해방을 결국엔 가진게 아닐까?',
    reason: '첫 문장이 좋아서 읽어 봤음. 공감 못할 사람이 있을까',
    // reviewLink: 'https://brunch.co.kr/@yourid/123',
    // reviewSite: '브런치'
    date: '2025-01-02'
  },
  {
    id: 2,
    access: "public",
    title: '이방인',
    author: '알베르 카뮈',
    status: 'read',
    image: 'https://minumsa.minumsa.com/wp-content/blogs.dir/2/files/bookclub-shop/%EB%8C%80%EC%A7%80-257-500x500.png',
    rating: 5,
    tags: ['고전', '문학'],
    review: '사실 시간이 갈 수록 카뮈의 부조리 철학이 더 와닿는 것 같다. 카뮈의 철학을 3단계로 나누자면, 그 첫번째에 해당하는 책. 잘 읽는다면, 인간중심적, 사회종속적 사고를 흔들 수 있는 책이라고 생각함. 내포하는 의미가 많기 때문에 짧지만 천천히 읽어봐야함.',
    reason: '실존주의에 관심 생겼을 때 가장 처음 접해본 문학.',
    reviewLink: 'https://brunch.co.kr/@yyubin/3',
    reviewSite: '브런치',
    date: '2025-04-01'
  },
  {
    id: 3,
    access: "public",
    title: '변신',
    author: '프란츠 카프카',
    status: 'read',
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791164456314.jpg',
    rating: 4,
    tags: ['고전', '문학'],
    review: '인간 존재의 의미가 무엇일까. 부조리한 세상에서 인간이 이해할 수 없는 상황에 처하더라도 스스로 자신의 존재를 정의해야만 한다는 교훈을 담은 책이다. 아주 실존주의적. 처음 읽었을 땐, "본인의 가치 창출을 해야만 존재로서 인정 받을 수 있다" 고 생각했지만 지금은 아니다. 그냥 그레고르가 벌레로서의 삶을 긍정하는게 최선이었을거라고 생각함',
    reason: '읽어보려던 문학 작품 중 가장 짧아서 골랐었다.',
    reviewLink: 'https://velog.io/@cassidy/%EB%B3%80%EC%8B%A0-%EC%8B%A4%EC%A1%B4%EC%A3%BC%EC%9D%98',
    reviewSite: '벨로그',
    date: '2024-11-22'
  },
  {
    id: 4,
    access: "public",
    title: '오만과 편견',
    author: '제인 오스틴',
    status: 'read',
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788937460883.jpg',
    rating: 4,
    tags: ['고전', '문학'],
    review: '요즘 흔히들 읽는 로판 웹소설의 고전판. 클리셰적이지만 클래식. 솔직히 아주 취향까지는 아니다.. 내가 가치를 못알아보는게 맞다.',
    reason: '민음사 유튜브.. 보다가 읽어봄',
    date: '2025-04-21'
  },
  {
    id: 5,
    title: '사람은 무엇으로 사는가',
    author: '레프 톨스토이',
    status: 'reading',
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791191280630.jpg',
    tags: ['고전', '종교', '문학'],
    review: '읽고 있긴 하지만, 너무 종교적이라 사실 공감이 안된다.. 완독 할 수 있을까?',
    reason: '후기 톨스토이를 읽어보고 싶어서 고름',
    date: '2025-04-03'
  },
  {
    id: 6,
    access: "public",
    title: '동물농장',
    author: '조지 오웰',
    status: 'read',
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788937460050.jpg',
    rating: 4,
    tags: ['고전', '문학'],
    review: '마르크스와 레닌을 상징하는게 돼지들이다. 기존 문제있는 구조를 허물고 새로 만든 구조 또한 다를 게 없었음. 후기 구조주의나 해체주의가 생각나기도 한다. 이념과 사상으로 어떻게 대중을 세뇌시키는지 볼 수 있다.',
    reason: '어떤 방향으로든 정치적 작품들은 선호하지 않지만, 선물받아서 읽게 되었다.',
    date: '2025-04-04'
  },
  {
    id: 7,
    access: "public",
    title: '자유론',
    author: '존 스튜어트 밀',
    status: 'read',
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791187142447.jpg',
    rating: 5,
    tags: ['고전', '철학'],
    review: '스무 살 부터 스물 네살까지는 일년에 한번 이상씩 읽었던 책. 어려운 일이 있을 때 정신적 기반이 되어주기도 한 책이다. 어렵지 않게 현실적 문제들과 대조해 볼 수 있고 사회적 경계에서의 선을 이론적으로 배울 수 있다.',
    reason: '스스로의 권리가 의심 됐을 때 읽게 되었음',
    date: '2025-07-01'
  },
  {
    id: 8,
    title: '신곡',
    status: 'to-read',
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788956592169.jpg',
    tags: ['고전', '종교', '문학'],
    reason: '서구 기독교 문명을 집대성한 작품. 순수 고전문학-희곡으로서 난이도도 낮진 않지만, 언젠가 읽어보고 싶음'
  },
  {
    id: 10,
    title: '니코마코스 윤리학',
    author: '아리스토텔레스',
    status: 'reading',
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791139701777.jpg',
    rating: 0,
    tags: ['고전', '철학'],
    review: '읽고 있지만, 사실 최근 근-현대 철학을 보며 아리스토텔레스가 주장한 여러 철학에 진심으로 공감이 안돼서 읽기를 미루는 중',
    reason: '아리스토텔레스의 실천적 지혜가 담긴 책이라 읽어보고 싶었다.',
    date: '2025-06-06'
  },
  {
    id: 11,
    access: "public",
    title: '명상록',
    author: '마르쿠스 아우렐리우스',
    status: 'read',
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791187142379.jpg',
    rating: 4,
    tags: ['고전'],
    review: '고대 시대 책의 단점이라면, 모든 논리가 일관되지 않는다는 것. 하지만 당시 위대한 군주이자 황제였던 자의 스토아 철학에 기반한 삶의 태도를 볼 수 있다는 것에 이미 가치가 높다.',
    reasone: '이미 읽었던 책이지만, 책임과 의무를 어떻게 해내는 지 고민될 때 종종 다시 읽게 된다',
    date: '2024-11-27'
  },
  {
    id: 13,
    access: "public",
    title: '데미안',
    author: '헤르만 헤세',
    status: 'read',
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788937460449.jpg',
    rating: 5,
    tags: ['고전', '문학'],
    review: '완벽히 이해하지 못하는 책 중 하나다. 가장 주목했던 키워드는 "악의 평범성"이다. 선악은 분명하지 않고 인간이란 입체적이고 다층적이다. 스스로와 타인에게 있어 그러한 시선을 가지고 사는게 성숙함이라고 헤르만 헤세는 말한다. 이러한 과정을 하나의 성장소설로 표현한게 아닌가 싶다. 문학작품들이 으레 그렇듯 독자의 성찰과 고민 없이는 쉽게 의미가 느껴지지 않는 것 같다.',
    reason: '별다른 동기는 없고, 궁금했고 한가했다.',
    date: '2024-10-26'
  },
  {
    id: 14,
    access: "public",
    title: '인간 실격',
    author: '다자이 오사무',
    status: 'read',
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788937461033.jpg',
    rating: 5,
    tags: ['문학'],
    review: '"인간 소외" 라는 개념을 소설 형식으로 잘 느껴볼 수 있었다. 불화와 정체성의 혼란, 우울감, 미성숙함 등. 사회가 요구하는 개인의 정상성/대립을 느껴볼 수 있었음. 사실 이런 인간상(요조)은 이미 현실에서 보기에도 어렵지 않다고 생각한다.',
    reason: '해당 주인공을 싫어하고 이해할 수 없다는 서평을 여럿본 후, 읽어보고 싶었다.',
    reviewLink: 'https://brunch.co.kr/@yyubin/2',
    reviewSite: '브런치',
    date: '2025-04-09'
  }, 
  {
    id: 15,
    title: '존재와 무',
    status: 'to-read',
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788949705255.jpg',
    tags: ['철학'],
    reason: '사르트르의 사상 및 삶의 방식의 방향성을 결정한 초기작이기에 읽어보고 싶다. 현상학적 존재론으로 개인의 존재 앞에서 개인의 실존에 대해 이야기함. 난이도가 낮지 않아서, 시간을 좀 두고 천천히 읽어야 할 듯하다.'
  },
  {
    id: 16,
    access: "public",
    title: '달과 6펜스',
    author: '서머싯 몸',
    status: 'read',
    tags: ['문학'],
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788931001921.jpg',
    rating: 4,
    review: '열린 결말이 가장 기억에 남는다. 대부분의 철학서나 교양서, 종종 문학작품도 생각을 한쪽으로 귀결시키도록 유도하는데 아무런 도덕적 판단을 하지 않고 끝냄. 그래서 이에 대해 혼자 생각해야 함. 이 과정이 재미있긴 했고, 개인의 자유와 책임에 대해 "자유론"과 달리 더 문학적으로 느낄 수 있는 작품. 6펜스(현실)에서 달(이상)으로 가는 길은 나에게도 힘들지만 타인에게도 힘들다.',
    reason: '문창과 친구가 추천해줬다.',
    reviewLink: 'https://brunch.co.kr/@yyubin/4',
    reviewSite: '브런치',
    date: '2025-04-12'
  },
  {
    id: 17,
    access: "public",
    title: '여름',
    author: '이디스 워튼',
    status: 'read',
    tags: ['문학'],
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788937463686.jpg',
    rating: 4,
    review: '생각보다 생각할 게 많았다. 자신의 삶과 선택을 비통하게만 보지 않고 주어진 상황에서 본인의 삶을 긍정하고 마주하는 태도는 희귀하다. 근데 물론 혹자들은 합리화이자 본인의 삶을 책임지지 못하는 약한 인간상이라고도 느낄 수 있을 거 같긴함',
    reason: '너무 무겁고 강한 사유만 들어있는 책들을 한창 읽다가 리프레시 하고 싶어서 고름',
    reviewLink: 'https://brunch.co.kr/@yyubin/1',
    reviewSite: '브런치',
    date: '2025-04-06'
  },
  {
    id: 18,
    title: '카라마조프가의 형제들',
    author: '표도르 도스토옙스키',
    status: 'reading',
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788937486067.jpg',
    tags: ['고전', '문학'],
    review: '2부 중간까지 읽었는데, 저자 특유의 여백 없는 만연체가 조금 지쳐서.. 천천히 봐야할 듯',
    reason: '나약한 지식인, 허위와 위선, 이기주의에 대한 도스토옙스키의 비판이 담겨있음. 벽돌책이지만 읽을 가치가 있다고 생각했다..',
    date: '2025-04-11'
  },
  {
    id: 19,
    access: "public",
    title: '마흔에 읽는 쇼펜하우어',
    author: '강용수',
    status: 'read',
    tags: ['철학'],
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791192300818.jpg',
    rating: 3,
    review: '가볍게 읽기에는 좋았다. 하지만 쇼펜하우어 철학을 정말로 느끼고 싶은거라면 다른 책을 읽는게 나을 것 같다.',
    reason: '밀리의 서재에서 눈에 띄어서 가벼운 마음으로 읽음',
    date: '2024-11-27'
  },
  {
    id: 20,
    access: "public",
    title: '차라투스트라는 이렇게 말했다',
    author: '프리드리히 니체',
    status: 'read',
    rating: 5,
    image: 'https://chedulife.com.au/wp-content/uploads/%EC%A7%9C%EB%9D%BC%ED%88%AC%EC%8A%A4%ED%8A%B8%EB%9D%BC%EB%8A%94-%EC%9D%B4%EB%A0%87%EA%B2%8C-%EB%A7%90%ED%96%88%EB%8B%A4.jpg',
    tags: ['철학', '고전', '문학'],
    review: '정말 이해하고 싶다면 치밀하게 읽어야 한다. 이를 이해하기 위해 가볍게는 인터넷 블로그 부터 논문까지 살펴봤음.. 만약 실존주의 개념이 익숙하지 않다면 다른 책을 먼저 읽어야 할 듯. 함축되어 있고 내포되어 있는 문장과 단어가 많다. 이와 별개로 니체의 여러 사상이 담겨 그에 대한 이해를 목표로 한다면 충분할 듯 하다. 하지만 친절하지 않으니 어쩌면 니체의 다른 책을 먼저 읽는 것도 좋을 듯 하다.. "도덕의 계보" 라던가.. 개인적으론 애정이 있어서 블로그에 각 부별로 내가 찾아본 내용들을 정리했다.',
    reason: '스무살때 도전하고 이해 안되서 미뤄뒀다 다시 읽은 책', 
    reviewLink: 'https://brunch.co.kr/@yyubin/5',
    reviewSite: '브런치',
    date: '2025-04-12'
  },
  {
    id: 21,
    access: "public",
    title: '구조주의와 그 이후',
    status: 'read',
    rating: 5, 
    author: '김종우',
    tags: ['철학'],
    reason: '후기 구조주의-해체주의를 기반으로한 포스트 모더니즘 사상으로 넘어가기 전에, 그 기저가되는 구조주의를 이해하기 위해 읽어보는 중',
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788952206473.jpg',
    date: '2025-08-23',
    review: "최초의 구조주의는 소쉬르의 언어론에서 시작한다고 볼 수 있겠다. 구조주의는 현상학과 달리 개별 대상에 관심을 두지 않고 그 대상을 둘러싼 구조와 체계에 초점을 맞춘다. 이때 주체의 의식은 중요히 여기지 않는다. 이게 구조주의 비판자들에게서 주로 제기되는 문제이다. 구조언어학에선 언어가 규칙에 따라 지배되는 비 자율적 존재이지만, 사실 실제 언어활동에서 말하는 주체는 상황마다 달리 나타나는 자율적 존재라는 것이다. 결론적으로 구조주의 이후는 후기 구조주의 흐름과 현상학 흐름으로 나뉘었다. 내가 목표로 하던 구조주의의 개괄과 흐름, 기본적인 원리에 대해선 알게 되었다고 생각한다. 구조주의 자체에 대한 특히, 다음 스텝(후기 구조주의나 포스트 모더니즘)의 발판으로 구조주의의 기저가 되는 이론을 살펴보기에 적절한 책이라고 생각한다. 애초에 국내에 구조주의 자체에 대한 저서도 많이 모자란듯 하다.. 특히 일반인을 대상으로 한 것은 더 그렇다. 아주 만족스럽게 읽었고, 기억하면 좋을 것 같은 부분은 노션에 따로 정리도 해뒀지만, 언젠간 다시 한번 열어서 봐야할 듯"
  },
  {
    id: 22,
    access: "public",
    title: '광기의 역사',
    status: 'to-read',
    author: '미셸 푸코',
    tags: ['철학'],
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788930040518.jpg',
    reason: '푸코는 광기를 단순한 의학적 사실이 아니라, 사회가 비정상으로 규정한 존재를 배제하기 위해 역사적으로 만들어낸 개념이라 보았다. 우리가 느끼는 정상성은 인공적이고 인위적인 인간 문명의 산물이라는데에, 개인적으로 요즘은 동의한다. 그래서 읽어보고 싶음.',
    date: '2025-08-18'
  },
  {
    id: 23,
    access: 'private',
    title: 'ostep',
    status: 'reading',
    author: 'Remzi H.Arpaci-Dusseau , Andrea C. Arpaci-Dusseau',
    tags: ['기술'],
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791156007395.jpg',
    reason: '운영체제 개괄 부터 심층적 부분까지 다시 한번 공부해보기 위해 읽고 있음. 전공서라 그런지 독파하기란 쉽지 않다.. 과제까지 제시해주고, pdf로 풀려있어서 접근성도 좋다.',
    date: '2025-06-10'
  },
  {
    id: 24,
    access: "public",
    title: '데이터 중심 애플리케이션 설계',
    status: 'read',
    author: '마틴 클레프만',
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791158390983.jpg',
    tags: ['기술'],
    reason: '요즘 진행중인 사이드 프로젝트들에서 데이터와 그들을 다루는 시스템들에 대한 이해가 모자라다고 느껴서 읽고 있다. 여러 시스템들의 기저가 되는 원리를 설명하고 선택을 하는데에 있어서 실질적으로 사용할 수 있는 판단 기준, 어떤 지표를 고려해야 하는지 까지 구체적으로 제시해준다.',
    rating: 5,
    review: '데이터베이스 내부 구조, 여러 데이터베이스들 간의 차이점, 분산 환경에서의 고려사항, 분산환경에서의 데이터베이스 구조 등등을 자세히 알려줌. 근데 현재 분산환경에 대한 경험이 적다보니 원리적으론 이해가 되지만, 크게 와닿진 않았다.. 나중에 아마 해당 부분을 필요로 할 상황이 올 것 같은데, 그때가 되면 다시 읽어 봐야 할듯? 하지만 상용 데이터베이스들 간의 차이가 어떻게 생기고, CAP이나 ACID 등등 데이터베이스 이론들을 어떻게 챙기고 구성하는지, 분산 환경에서의 데이터베이스 트랜잭션이 어떤걸 고려해야하는 지 등등 상세히 알려줘서 감사할 따름임.. 보다 보면 재미도 있었음. 원래는 유사 orm 같은거 만드느라 이해를 키우려고 본 것이었는데 그 이상을 얻어가긴 한 것 같다. 더 시간을 잡아서 치밀하게 정리하며 읽으면 더 좋을 것 같기도 해서 그 부분은 스스로에게 아쉬움',
    date: '2025-09-04'
  },
  {
    id: 26,
    access: "public",
    title: '구의 증명',
    status: 'read',
    author: '최진영',
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/480D230526710.jpg',
    tags: ['문학'],
    rating: 3,
    reason: '평가, 특히 소재에 대한 호불호가 아주 강하게 나타나서 궁금해서 읽어봤다.',
    review: '개인적으로 소재(식인)가 파격적이지만 그렇게 주목할 만한 부분은 아닌 것 같다. 담이 구를 떠나보내는 과정이 그만큼 고통스럽게 표현된 것이라 생각할 뿐임.. 근데 순수하게 전개의 매끄러움과 개연성이 모자라다고 느껴졌다..',
    date: '2025-06-15'
  },
  {
    id: 27,
    access: 'private',
    title: '시지프 신화',
    status: 'reading',
    author: '알베르 카뮈',
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788937463433.jpg',
    tags: ['고전', '철학', '문학'],
    reason: '이미 읽긴 했다. 하지만 오래된 기억이라 다시 읽고 있다.. 시론에 나오는 부분이 전에 읽었을 때와 달리 다르게 느껴짐. `내가 나의 존재에 대하여 갖는 확신과 내가 그 확신에 부여하려는 내용 사이에 가로놓인 단절은 결코 메워질 수 없을 것이다. 나는 나 자신에게 영원히 이방인일 것이다.`',
    date: '2025-08-13'
  },
  {
    id: 28,
    access: "private",
    title: 'CSAPP',
    status: 'to-read',
    author: "Randal E. Bryan , David R. O'Hallaron",
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9781292101767.jpg',
    tags: ['기술'],
    reason: '책은 이미 있다. 변명이지만 먼저 읽어야 할 책이 많아서 미루고 있다.',
  },
  {
    id: 29,
    access: "private",
    title: '컴퓨터 네트워킹 하향식 접근',
    status: 'reading',
    author: 'James F. Kurose, Keith W. Ross',
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9789813350212.jpg',
    tags: ['기술'],
    reason: '이 역시 cs 분야를 더 잘 공부하기 위해 읽고 있음. 음 쉽지 않다. 그래도 읽어본 네트워킹 책 중에선 이해가 제일 잘 되는 듯 하다',
    date: '2025-06-20'
  },
  {
    id: 30,
    access: "private",
    title: '코딩 인터뷰 완전 분석',
    status: 'reading',
    author: '게일 라크만 맥도웰',
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788966263080.jpg',
    tags: ['기술'],
    reason: '초반부를 읽자마자 스스로 얼마나 해당 역량들이 모자랐던건지 바로 체감할 수 있었다. 900장이 넘기에 정말 읽기 어려워서 완독을 장담할 수 있을까.. 싶긴하지만 이를 조금이나마 읽고나서 다시 알고리즘을 공부하기 시작했다..',
    date: '2025-01-12'
  },
  {
    id: 31,
    access: "private",
    title: 'JVM 밑바닥까지 파헤치기',
    status: 'reading',
    author: '저우즈밍',
    tags: ['기술'],
    reason: 'jvm 내부 원리를 처음부터 혼자 탐독하기란 어렵다. 아주 예전에 절판된 해외 직수입 서양서들은 많지만 비교적 번역도 되어있어 접근성이 좋아 선택했다. 이를 통해 모든 jvm 스펙에 대해서 알 수는 없지만 혼자 탐험할 수 있는 원리와 환경을 알려준다는 데에서 이미 가치가 크다고 생각',
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788966264414.jpg',
    date: '2025-08-05'
  },
  {
    id: 32,
    access: "public",
    title: 'Do it! 딥러닝 입문',
    date: '2025-05-26',
    status: 'read',
    author: '박해선',
    rating: 5,
    tags: ['기술'],
    reason : '순수하게 AI 원리가 궁금해서 읽기 시작함',
    review: 'AI 생태계의 라이브러리 사용법만 가르쳐주는게 아닌, 초기 알고리즘에 대한 수식 및 증명까지 정리되어 있다. 게다가 이 역시도 쉽게 풀어 설명되어 있음. 저자가 유튜브로 강의도 해줌.. 재미있게 볼 수 있었다.',
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791163031093.jpg',
  },
  {
    id: 33,
    access: "private",
    title: '의지와 표상으로서의 세계',
    date: '2025-08-20',
    status: 'reading',
    author: '아르투어 쇼펜하우어',
    tags: ['철학'],
    reason: '예전에 읽으려고 시도하다가, 저자가 서론에서 칸트를 모르면 읽지마라, 그리고 원서로 읽으라고 으름장을.. ㅋㅋㅋ 두셔서 미뤘다. 그렇다고 지금 칸트에 대해서 아주 잘 아는건 아니지만.. 쇼펜하우어의 칸트 비판이 해당 책 부록으로 있어서 그 부분을 읽은 후 다시 도전하는 중',
    review: '',
    image: 'https://image.yes24.com/goods/73619945/XL'
  },
  {
    id: 34,
    access: "public",
    title: '로버트 나이스트롬의 인터프리터 in Java, C',
    date: '2025-08-21',
    status: 'reading',
    author: '로버트 나이스트롬',
    tags: ['기술'],
    reason: '사이드 프로젝트로, 내가 좋아하는 게임의 전략 및 추천 시스템을 위해 메타 데이터를 구성하여 추후 그래프 데이터베이스를 활용해보려고 했음. 그리고 요즘 또 개발에 몰두중인게, JPA 지원하는 DDL 생성기인데.. 이 역시도 중간언어, DSL, 런타임에 대한 지식이 더 필요할 것 같았다. 뭔가 일을 너무 벌이는 기분이지만, 지금은 문제없다.',
    review: '',
    image: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791140707386.jpg'
  },
  {
    id: 35,
    access: "public",
    title: "노인과 바다",
    date: "2025-09-06",
    status: "read",
    rating: 4,
    author: "어니스트 해밍웨이",
    tags: ['문학'],
    reason: '해밍웨이의 생전 마지막 출간 작품인데, 이게 그의 삶에서 어떤 시사하는 바가 있을 지 궁금했음..',
    review: '반드시 교훈적으로 작품을 해석하고 싶지는 않기도 하다. 노인은 항해를 통해 원하는 바를 얻었지만 여러 방해(상어들)로 인해 사실 결과론적으론 만족스러워 할 수는 없었다. 이는 해밍웨이가 자신의 작품활동이 불완전한 성공이라고 느끼는 것이 투영된 걸까? 아니면 불완전한 결과를 피할 수 없기에 이를 받아들여야 한다는 걸까? 아니면 그냥 영웅적으로 묘사되는 산티아고를 존경하기만 하면 되는 걸까? 결과 없이 투쟁만으로도 인간의 존엄을 드러낼 수 있다는 건가? ㅋㅋㅋ 사실 다 실존하는 해석이지만 개인적으로 당장 결론을 내리고 싶진 않다. 논지에는 안 맞지만, 과도한 사색과 성찰이 오히려 방향을 흐트러트리거나 성정을 저해하는 면도 있는 것 같아 이런 종류의 생각들을 좀 내려둘 필요도 있는 것 같다. 그래서 이에 대한 음 개인적 결론은 추후에 만들어 볼 듯.',
    image: 'https://image.yes24.com/goods/6157159/XL'
  },
  {
    id: 36,
    access: "public",
    title: "Architecture of a Database System",
    date: "2025-09-08",
    status: "read",
    rating: 5,
    author: "Joseph M. Hellerstein, Michael Stonebraker and James Hamilton",
    tags: ['논문', '기술'],
    reason: 'DDIA 이후 실제 상용 DBMS 시스템의 내부 구현에 대해 자세히 알아보고 싶어서',
    review: "", 
    image: '/ADS.png',
    reviewLink: 'https://dsf.berkeley.edu/papers/fntdb07-architecture.pdf',
    reviewSite: '논문 바로가기',
  }
];
